apiVersion: apps/v1
kind: Deployment

metadata:
  name: kk-payments
  labels:
    app: kk-payments
    week: "8"

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kk-payments

  template:
    metadata:
      labels:
        app: kk-payments
        version: "1.0.0"

    spec:
      imagePullSecrets:
      - name: kijani-registry-credentials

      containers:
      - name: kk-payments
        image: docker.io/nancykanyingi/kk-payments:1.0.0-dev-f0ace0d
        ports:
        - containerPort: 3001

        env:
        - name: NODE_ENV
          value: "production"

        - name: PORT
          value: "3001"

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "500m"
